"""Email forwarding rules management API."""

import datetime
import uuid
from typing import Optional
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from atulya_launch import utils
from atulya_launch.web.auth import get_current_user
from atulya_launch.web.database import connect

router = APIRouter(prefix="/api/email/forwarding", tags=["email-forwarding"])


class ForwardingRuleCreate(BaseModel):
    source: str
    destination: str
    enabled: bool = True
    keep_copy: bool = False
    description: Optional[str] = None


def _generate_postfix_forwarding(domain: str, rules: list) -> str:
    lines = [
        f"# Email forwarding rules for {domain}",
        "# Generated by Atulya-Launch",
        "",
    ]
    for rule in rules:
        if rule.get("enabled"):
            alias_line = f"{rule['source']}@{domain}  {rule['destination']}"
            lines.append(alias_line)
    return "\n".join(lines)


def _apply_postfix_forwarding(domain: str, rules: list):
    if not utils.is_linux():
        return
    from pathlib import Path
    vmap_path = Path(f"/etc/postfix/virtual_{domain}")
    content = _generate_postfix_forwarding(domain, rules)
    vmap_path.parent.mkdir(parents=True, exist_ok=True)
    vmap_path.write_text(content + "\n")
    utils.run_command(["postmap", str(vmap_path)], check=False)
    main_cf = Path("/etc/postfix/main.cf")
    if main_cf.exists():
        cf_content = main_cf.read_text()
        if "virtual_alias_maps" not in cf_content:
            alias_maps_line = f"virtual_alias_maps = hash:/etc/postfix/virtual_{domain}"
            main_cf.write_text(cf_content + "\n" + alias_maps_line + "\n")
    utils.service_action("reload", "postfix")


@router.get("/{domain}")
def list_forwarding(domain: str, user: dict = Depends(get_current_user)):
    with connect() as conn:
        rows = conn.execute(
            "SELECT id, source, destination, enabled, keep_copy, description, created_at, updated_at FROM email_forwarding_rules WHERE domain = ?",
            (domain,),
        ).fetchall()
    rules = [dict(r) for r in rows]
    for r in rules:
        r["enabled"] = bool(r["enabled"])
        r["keep_copy"] = bool(r["keep_copy"])
    return {"domain": domain, "rules": rules}


@router.post("/{domain}")
def add_forwarding_rule(domain: str, body: ForwardingRuleCreate, user: dict = Depends(get_current_user)):
    if not body.source or not body.destination:
        raise HTTPException(status_code=400, detail="source and destination are required")
    rule_id = str(uuid.uuid4())[:8]
    now = datetime.datetime.now().isoformat()
    with connect() as conn:
        conn.execute(
            """INSERT INTO email_forwarding_rules (id, domain, source, destination, enabled, keep_copy, description, created_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
            (rule_id, domain, body.source, body.destination, 1 if body.enabled else 0,
             1 if body.keep_copy else 0, body.description or "", now),
        )
        rows = conn.execute(
            "SELECT id, source, destination, enabled, keep_copy, description FROM email_forwarding_rules WHERE domain = ?",
            (domain,),
        ).fetchall()
    _apply_postfix_forwarding(domain, [dict(r) for r in rows])
    return {"status": "created", "rule_id": rule_id}


@router.put("/{domain}/{rule_id}")
def update_forwarding_rule(domain: str, rule_id: str, body: ForwardingRuleCreate, user: dict = Depends(get_current_user)):
    now = datetime.datetime.now().isoformat()
    with connect() as conn:
        row = conn.execute(
            "SELECT id FROM email_forwarding_rules WHERE id = ? AND domain = ?",
            (rule_id, domain),
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Rule not found")
        conn.execute(
            """UPDATE email_forwarding_rules
               SET source = ?, destination = ?, enabled = ?, keep_copy = ?, description = ?, updated_at = ?
               WHERE id = ?""",
            (body.source, body.destination, 1 if body.enabled else 0,
             1 if body.keep_copy else 0, body.description or "", now, rule_id),
        )
        rows = conn.execute(
            "SELECT id, source, destination, enabled, keep_copy, description FROM email_forwarding_rules WHERE domain = ?",
            (domain,),
        ).fetchall()
    _apply_postfix_forwarding(domain, [dict(r) for r in rows])
    return {"status": "updated", "rule_id": rule_id}


@router.delete("/{domain}/{rule_id}")
def delete_forwarding_rule(domain: str, rule_id: str, user: dict = Depends(get_current_user)):
    with connect() as conn:
        row = conn.execute(
            "SELECT id FROM email_forwarding_rules WHERE id = ? AND domain = ?",
            (rule_id, domain),
        ).fetchone()
        if not row:
            raise HTTPException(status_code=404, detail="Rule not found")
        conn.execute("DELETE FROM email_forwarding_rules WHERE id = ?", (rule_id,))
        rows = conn.execute(
            "SELECT id, source, destination, enabled, keep_copy, description FROM email_forwarding_rules WHERE domain = ?",
            (domain,),
        ).fetchall()
    _apply_postfix_forwarding(domain, [dict(r) for r in rows])
    return {"status": "deleted", "rule_id": rule_id}
