"""Hotlink protection API for sites."""

import datetime
from typing import Optional, List
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from atulya_launch import utils
from atulya_launch.web.auth import get_current_user

router = APIRouter(prefix="/api/sites/{domain}/hotlink", tags=["hotlink"])

HOTLINK_FILE = utils.CONFIG_DIR / "hotlink.json"


class HotlinkConfig(BaseModel):
    enabled: bool = True
    allowed_referrers: List[str] = []
    block_action: str = "403"
    allow_direct: bool = True
    allow_empty_referrer: bool = False
    excluded_paths: List[str] = []


def _load_hotlink() -> dict:
    if HOTLINK_FILE.exists():
        import json
        return json.loads(HOTLINK_FILE.read_text())
    return {"domains": {}}


def _save_hotlink(data: dict):
    HOTLINK_FILE.parent.mkdir(parents=True, exist_ok=True)
    import json
    HOTLINK_FILE.write_text(json.dumps(data, indent=2))


def _generate_nginx_rules(domain: str, config: HotlinkConfig) -> str:
    lines = [
        f"# Hotlink protection for {domain}",
        f"# Generated by Atulya-Launch",
        "",
        f"map $http_referer $valid_referrer {{",
        f"    default 0;",
    ]
    for ref in config.allowed_referrers:
        lines.append(f'    "~*{ref}" 1;')
    if config.allow_empty_referrer:
        lines.append(f'    "" 1;')
    lines.append(f"}}")
    lines.append(f"")
    lines.append(f"location ~* \\.(jpg|jpeg|png|gif|webp|bmp|ico|svg|mp4|mp3|avi|mov|flv|wmv|css|js)$ {{")
    lines.append(f"    valid_referers none blocked {(' '.join(config.allowed_referrers))};")
    if not config.allow_direct:
        lines.append(f"    if ($invalid_referer) {{")
        if config.block_action == "403":
            lines.append(f"        return 403;")
        elif config.block_action == "redirect":
            lines.append(f"        return 302 /hotlink-denied.html;")
        else:
            lines.append(f"        return 444;")
        lines.append(f"    }}")
    lines.append(f"}}")
    return "\n".join(lines)


@router.get("")
def get_hotlink(domain: str, user: dict = Depends(get_current_user)):
    data = _load_hotlink()
    config = data.get("domains", {}).get(domain, {
        "enabled": False,
        "allowed_referrers": [],
        "block_action": "403",
        "allow_direct": True,
        "allow_empty_referrer": False,
        "excluded_paths": [],
    })
    return {"domain": domain, "hotlink": config}


@router.put("")
def set_hotlink(domain: str, body: HotlinkConfig, user: dict = Depends(get_current_user)):
    if body.block_action not in ("403", "redirect", "drop"):
        raise HTTPException(status_code=400, detail="block_action must be one of: 403, redirect, drop")
    data = _load_hotlink()
    data.setdefault("domains", {})[domain] = {
        "enabled": body.enabled,
        "allowed_referrers": body.allowed_referrers,
        "block_action": body.block_action,
        "allow_direct": body.allow_direct,
        "allow_empty_referrer": body.allow_empty_referrer,
        "excluded_paths": body.excluded_paths,
        "updated_at": datetime.datetime.now().isoformat(),
    }
    _save_hotlink(data)
    snippet_path = Path(f"/etc/nginx/snippets/hotlink-{domain}.conf")
    snippet_path.parent.mkdir(parents=True, exist_ok=True)
    if body.enabled:
        snippet_path.write_text(_generate_nginx_rules(domain, body))
    elif snippet_path.exists():
        snippet_path.unlink()
    if utils.is_linux():
        utils.run_command(["nginx", "-t"], check=False)
        utils.service_action("reload", "nginx")
    return {"status": "updated", "domain": domain, "enabled": body.enabled}


from pathlib import Path
